### ISSUE TITLE
If you are not familiar with Jupyter notebooks... link in Chapter 1 does not work.

### ISSUE THREAD

**Issue by johnallred** [AllenDowney/ThinkPython#10]
The chapter 1 link "If you are not familiar with Jupyter notebooks, [click here for a short introduction](https://colab.research.google.com/github/AllenDowney/ThinkPython/blob/v3/chapters/jupyter_intro.ipynb)." shows the error:

Notebook not found

There was an error loading this notebook. Ensure that the file is accessible and try again.

Ensure that you have permission to view this notebook in GitHub and authorize Colaboratory to use the GitHub API.
https://github.com/AllenDowney/ThinkPython/blob/v3/chapters/jupyter_intro.ipynb

Could not find jupyter_intro.ipynb in https://api.github.com/repos/AllenDowney/ThinkPython/contents/chapters?per_page=100&ref=v3
wb@https://ssl.gstatic.com/colaboratory-static/common/3e1e9f5191f3657451c6f18bfa55805d/external_polymer_binary.js:93:517
zL@https://ssl.gstatic.com/colaboratory-static/common/3e1e9f5191f3657451c6f18bfa55805d/external_polymer_binary.js:2351:68
FLa/<@https://ssl.gstatic.com/colaboratory-static/common/3e1e9f5191f3657451c6f18bfa55805d/external_polymer_binary.js:2338:442
wa@https://ssl.gstatic.com/colaboratory-static/common/3e1e9f5191f3657451c6f18bfa55805d/external_polymer_binary.js:16:57
ua.prototype.next_@https://ssl.gstatic.com/colaboratory-static/common/3e1e9f5191f3657451c6f18bfa55805d/external_polymer_binary.js:14:195
laa/this.next@https://ssl.gstatic.com/colaboratory-static/common/3e1e9f5191f3657451c6f18bfa55805d/external_polymer_binary.js:17:48
b@https://ssl.gstatic.com/colaboratory-static/common/3e1e9f5191f3657451c6f18bfa55805d/external_polymer_binary.js:17:309

**Comment by AllenDowney** [comment]
Should be fixed now. Thanks for letting me know!
