### ISSUE TITLE
Many Python 2 Print statements are seen throughout the repository

### ISSUE THREAD

**Issue by DavidBowley** [AllenDowney/ThinkPython#12]
I noticed today when I tried to import the Structshape module from chapter 12.8 that it was erroring out. It turned out to be the Python 2 syntax for the Print statements, and when updated to Python 3 everything worked flawlessly.

I did a quick search through the repository and found there's quite a few of these still left. I wasn't sure if this was deliberate but on page 2 of ThinkPython there is the following line:

> This book is written for Python 3, but I include some notes about Python 2.

It's possible that some beginners may get confused about why the provided examples aren't working.

I've attached the results of my search with the filename and line number in a text file (hopefully removed all the false positives from the comments where print is mentioned):
[Python 2 print statements.txt](https://github.com/AllenDowney/ThinkPython/files/14898836/Python.2.print.statements.txt)

On a side note - I'm absolutely loving the book (especially the exercises) and really appreciate that this is available as a free resource.

**Comment by AllenDowney** [comment]
Yes, some of the old examples in the repo are for Python 2. There are external links to them, so I don't want to remove them. But someone following links from the second edition should not encounter them.

Also, the second edition is still here for archival reasons, but the third edition is current: https://greenteapress.com/wp/think-python-3rd-edition/

**Comment by DavidBowley** [comment]
Thanks for the quick reply! That makes sense, I see the v3 branch now where all the new stuff is. I'm using an old PDF of the second edition which has links to thinkpython2.com, so when that domain wasn't working I Googled and found this repository and searched for the files manually, hence my finding the wrong ones as I looked in the Master branch.

I didn't realise there was a 3rd edition til today, I'll have to check that out also. Thanks again!
