### ISSUE TITLE
chapter 8: Error in Exercise and Solution

### ISSUE THREAD

**Issue by VersusFacit** [AllenDowney/ThinkPython#19]
Hi Think Python team,

I don't see contributing guidelines, so I'm leaving this issue as ample documentation and a proposed fix or two at the very least. 

Happy to provide the fixes myself if you're taking community contributions <3 

## Problem

I encountered a mere trifle -- an off by one logic error -- in your text and solution guide :)

<img width="600" alt="image" src="https://github.com/user-attachments/assets/0ac9b1df-dd2e-4742-b302-c72ecae1d6dd">

`re.findall`, however, gives `224`.

<img width="600" alt="image" src="https://github.com/user-attachments/assets/ced917e4-c963-43e3-b184-19bf49e6c1a7">

Note: I recognize I'm using a different regex than yours in the above screencap, but I _did_ double check they are equivalent / yield the same results.

### More context
Your solution snippet
```
def all_matches(filename, pattern):
    count = 0
    for line in open(filename):
        result = re.search(pattern, line)
        if result:
            count += 1
            print(line.strip())
            
    return count
```
uses `search` which only considers the first-encountered match in a string.

And lo, there is precisely one line with two matches (223 from your solution, 224 from using `findall`)
<img width="600" alt="image" src="https://github.com/user-attachments/assets/da2bd2d0-8600-407b-af54-bf4871900693">

### Sol 1: use `findall`
```
def all_matches(filename, pattern):
    count = 0
    for line in open(filename):
        result = re.findall(pattern, line)
        if result:
            count += len(result)
            print(line.strip())
            
    return count
```

### Sol 2: use loops to stay with `search`
```
def all_matches2(filename, pattern):
    count = 0
    compiled_pattern = re.compile(pattern) 
    with open(filename) as file:
        for line in file:
            result = compiled_pattern.search(line)
            while result:  # Continue searching until no more matches in the line
                count += 1
                # Search for the next match after the last one
                result = compiled_pattern.search(line, result.end())

    return count
```
Note had to reach for the compiled version to get a `Pattern` and use _its_ `search` method. `https://docs.python.org/3/library/re.html#re.Pattern.search`.

**Comment by AllenDowney** [comment]
That's a good point, but we don't know about lists until the next chapter, so I think I have to leave the solution not-quite-perfect.
