### ISSUE TITLE
Images in HTML are missing from notebook

### ISSUE THREAD

**Issue by jgfoster** [AllenDowney/ThinkPython#22]
In the HTML version of the book we have a label `4.11 Exercise` that says, "For example, here’s a rectangle that’s 80 units wide and 40 units tall." The image shows up in the HTML presentation but not in the Jupyter Notebook. The absence is especially pronounced in 4.12.3 where it says "Write an appropriately general set of functions that can draw flowers like this." Students are asking "Like what?"

Also, in the notebook the heading just says "Exercise" (the 4.11 is missing). 

Finally, note that the rhombus exercise has a heading starting with `##` while the other exercises have a heading starting with `###`.

**Comment by AllenDowney** [comment]
Thanks for letting me know. The issue with the heading is fixed now.

The others are more challenging: I have one set of notebooks that contain the text and solutions. From those I generate the HTML version, the notebooks without solutions (and the O'Reilly versions too, but at this point they have forked.)

Getting an image that's generated by the solutions into the notebooks without solutions is tricky -- at least to do it in a way that's maintainable going forward.

I'll see what I can do!

**Comment by jgfoster** [comment]
You can see my approach [here](https://github.com/jgfoster/ThinkPython/commit/3f949472caa03aa2e4471869aadd938eff3969d6).

**Comment by AllenDowney** [comment]
Looks good, but I need the notebooks to run on Colab, so I have to host those images somewhere. Maybe I'll pull them from the HTML version. But now I need logic to use the generated images in the solutions and the HTML version, and use the hosted images in the workbooks.

**Comment by jgfoster** [comment]
The images are hosted at the same place as your `.ipynb` files. See [here](https://colab.research.google.com/github/jgfoster/ThinkPython/blob/2249/chapters/chap04.ipynb) for my fork running on Colab.

**Comment by AllenDowney** [comment]
I don't understand what's going on there. The image tags refer to a directory called `images`, which I thought would be relative to the working directory in the Colab runtime, which doesn't contain such a directory. So why does this work, and where is that directory?

**Comment by jgfoster** [comment]
Colab is not hosting your files, they are only in GitHub. The URL we are providing to Colab tells it where to find the files. Compare your Colab URL to my Colab URL:

```
https://colab.research.google.com/github/AllenDowney/ThinkPython/blob/v3/chapters/chap04.ipynb
https://colab.research.google.com/github/jgfoster/ThinkPython/blob/2249/chapters/chap04.ipynb
```

The difference is in one case Colab is going to GitHub's user 'AllenDowney' and in the other case Colab is going to GitHub's user 'jgfoster' (also, your branch is 'v3' and mine is '2249'). [I hope you are okay with me forking your book and using it for my class. I've left your copyright and links to purchase the hardcopy.]

My GitHub has a 'blob' with the path `chapters/images` which is a sibling to `chapters/chap04.ipynb`, so Colab can find it. Your GitHub blob does not (yet!) have the `images` directory. Of course, you could put an absolute path to my images, but you probably want your own!

[I'm not quite sure which part of this you don't understand, so I've given a detailed answer to cover several bases (not meaning to be pedantic). I'm guessing it will be obvious when you pick up the missing piece—perhaps that I'm working with a fork.]

**Comment by AllenDowney** [comment]
Yes, no problem with forking, and thanks for the explanation -- the thing that confused me is that the image tag is treated as a URL relative to the URL in the notebook on GitHub rather than as a file path relative to the Colab file system. That's news to me!

That solves the problem of hosting the images, so that's good. I still have to work on some changes in the notebook processing pipeline, though.

**Comment by AllenDowney** [comment]
Well, it was a surprising pain in the neck to fix this, but fix it I did. @jgfoster, thanks again for the help.
