### ISSUE TITLE
Chapter 7 issues

### ISSUE THREAD

**Issue by jgfoster** [AllenDowney/ThinkPython#24]
Chapter 7 has the following:

```
%%expect NameError

y = y + 1
```

In fact, a bit earlier we have the following:

```
width, height, x, y = [0.54, 0.61, 0.07, 0.45]
```

This means that `y` has a value so does not result in a `NameError`. If you change the code to the following it gives the expected error:

```
z = z + 1
```

**Comment by AllenDowney** [comment]
This should be fixed now. Thanks for letting me know!

**Comment by jgfoster** [comment]
The first reference to `uses_only` should be `uses_any`.
