### ISSUE TITLE
Chapter 8, Wordle Exercise

### ISSUE THREAD

**Issue by jgfoster** [AllenDowney/ThinkPython#26]
"Of the words in the word list, how many could be the target word? Write a function called check_word that takes a five-letter word and checks whether it could be the target word."

I'm confused by this question. Does `check_word` take two strings as parameters (the word to check and the target)? Isn't there only one word that could be the target word? I assume something more complex than `==` is expected ("could" instead of "is"). Does this mean checking to see if one string is an anagram of another? Or is it that some letters are in the same place? Or is it enough that there is any overlap on the letters (like the `uses_any` example)? Or does the function just take the guess and see if it is in the word list?

**Comment by AllenDowney** [comment]
I have revised this question to clarify the intent. Does this do it?

> As a different example, suppose you have guessed the words SPADE and CLERK, and you've learned that E is in the word, but not in either of those positions, and none of the other letters appear in the word. Of the words in the word list, how many could be the target word? Write a function called check_word that takes a five-letter word and checks whether it could be the target word, given these guesses.

**Comment by jgfoster** [comment]
Yes, that helps. Thanks!
