### ISSUE TITLE
Discuss raw strings in chapter 8?

### ISSUE THREAD

**Issue by jgfoster** [AllenDowney/ThinkPython#28]
Chapter 8 has a couple examples of raw strings, and then at the end of the glossary introduces the term and gives a definition. I don't think the first use (`pattern = r'Mina|Murray'`) requires a raw string and the second example (`names = r'(?<!\.\s)[A-Z][a-zA-Z]+'`) is pretty complex (which is okay, since it is just a hint that there is a lot more functionality that is unexplored). 

I see three possibilities:
* Remove the first use and definition (we don't really need to cover raw strings).
* Add some minimal explanation of raw strings when its use is introduced (we don't generally wait for the glossary to explain new concepts).
* Leave as-is (the late explanation is sufficient).

I don't feel strongly, but it seems like something that was overlooked (or edited from a time when it was covered in more depth)!

**Comment by AllenDowney** [comment]
Yes, good point. Will fix!

**Comment by jgfoster** [comment]
And, while the issue is still open, the "String Methods" section is a bit sparse. For my class I'm adding a table of some common methods. The following was suggested by GitHub Copilot (if nothing else, this could be another question in the "Ask a virtual assistant" exercises):

| Method | Description |
|--------|-------------|
| str.lower() | Converts all characters in the string to lowercase. |
| str.upper() | Converts all characters in the string to uppercase. |
| str.capitalize() | Capitalizes the first character of the string. |
| str.title() | Converts the first character of each word to uppercase. |
| str.strip() | Removes leading and trailing whitespace. |
| str.lstrip() | Removes leading whitespace. |
| str.rstrip() | Removes trailing whitespace. |
| str.split(separator) | Splits the string into a list of substrings based on the given separator. |
| str.join(iterable) | Joins elements of an iterable with the string as a separator. |
| str.replace(old, new) | Replaces occurrences of a substring with another substring. |
| str.find(substring) | Returns the lowest index of the substring if found, otherwise returns -1. |
| str.index(substring) | Returns the lowest index of the substring if found, otherwise raises a ValueError. |
| str.startswith(prefix) | Checks if the string starts with the specified prefix. |
| str.endswith(suffix) | Checks if the string ends with the specified suffix. |
| str.isdigit() | Checks if all characters in the string are digits. |
| str.isalpha() | Checks if all characters in the string are alphabetic. |
| str.isalnum() | Checks if all characters in the string are alphanumeric. |
| str.islower() | Checks if all characters in the string are lowercase. |
| str.isupper() | Checks if all characters in the string are uppercase. |

**Comment by AllenDowney** [comment]
For the raw strings, I decided to make them optional, so the first mention is in "Ask a virtual assistant", and no longer in the glossary. And I offer two solutions to the Monte Cristo exercise, one using only the features in the chapter, and one using a regex with word boundaries.

The table of string methods is a good thing, but this chapter is already a little long, so I think I'll leave it out for now.
