### ISSUE TITLE
Chapter 10 - Debugging

### ISSUE THREAD

**Issue by jgfoster** [AllenDowney/ThinkPython#29]
The first numbered paragraph begins with `1)` while the remaining paragraphs begin with `2.`, `3.`, and `4.`. While this is a very minor inconsistency (which does not even show at all in VS Code), when rendered in Colab it is interpreted differently. The numbered paragraph is not indented and the following paragraph (which has leading spaces) is interpreted as code (which is where I was initially confused). The trivial fix is to replace `1)` with `1.`.

![Screenshot 2024-11-05 at 5 10 41 PM](https://github.com/user-attachments/assets/229a048e-ddb1-4c4a-96b3-f6a48ffca34a)

**Comment by AllenDowney** [comment]
Fixed. The change will propagate soon. Thanks!
