### ISSUE TITLE
Database keys are not iterable as described in 14.6 

### ISSUE THREAD

**Issue by mattall** [AllenDowney/ThinkPython#3]
"Many dictionary methods, like keys and items, also work with database objects. So does
iteration with a for statement." 

example code from book...
>>> import anydbm
>>> db = anydbm.open('captions.db', 'c')
>>> db['cleese.png'] = 'Photo of John Cleese doing a silly walk.'
for key in db:
    print key

running this code on my computer, the following error was thrown.
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'dbm.dbm' object is not iterable

Therefore, iteration with a for statement does not work on database objects as described above.

**Comment by AllenDowney** [comment]
You're right.  This code works in Python 3, but not Python 2.  I've made corrections in the text (see f026fb2b2deff279502f276b8a65532115db8f5a)

Thanks!
