### ISSUE TITLE
Chapter 10 - "Interlocking" Exercise

### ISSUE THREAD

**Issue by jgfoster** [AllenDowney/ThinkPython#30]
Does this have anything to do with dictionaries? It seems like an excellent exercise for chapters 8 or 9, so feels like it may have been left behind in a refactoring.

**Comment by AllenDowney** [comment]
I can be done without dictionaries, but it's much faster if you can use `word_dict` to check quickly whether the interlocked strings are words.

**Comment by jgfoster** [comment]
Ah, yes; thanks for the clarification. Like many students, I didn't read the problem carefully!
